version: "3.8"

services:
  postgres_db:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_DATABASE
    ports:
    - "5432:5432"
    volumes:
      - db:/var/lib/postgres
  app:
    depends_on:
      - postgres_db
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "r2dbc:postgresql://postgresdb:$DB_PORT/$DB_DATABASE",
              "spring.datasource.username" : "$DB_USER",
              "spring.datasource.password" : "$DB_PASSWORD",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: $DB_PASSWORD
    volumes:
      - pgadmin-data:/var/lib/pgadmin


volumes:
  db:
  pgadmin-data:



