spring:
    profiles:
        active: ${ACTIVE_PROFILE:dev}
management:
    endpoint:
        prometheus:
            enabled: true
    endpoints:
        web:
            exposure:
                include:  info, health, prometheus, metrics
    metrics:
        web:
            server:
                request:
                    autotime:



